server:
  port: 35000

spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    gateway:
      discovery:
        locator:
          # 开启服务发现
          enabled: true
          # 使用小写的服务id
          lower-case-service-id: true
      routes:
        - id: feignclient   # id 当前路由的唯一标识
          uri: lb://FEIGN-CLIENT  # 负载均衡路由转发
          predicates:   # 断言，可配置多个
            - Path=/feignclient/**  # Path断言，匹配以 feignclient 开头
          filters:      # 过滤器，可配置过个
            - StripPrefix=1         # 切断第一个前缀：如 http://localhost/feignclient/sayHi -> http://localhost/sayHi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 需要鉴权的路径
auth-filter:
  url-pattens: /authTest/**,/authTest2/**

jwt-auth:
  key: william
  issuer: willingoxjin
  security: TnZBd3n0qyabM2UP