server:
  port: 30002

spring:
  application:
    name: config-bus-server
  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: admin
    password: admin123
  cloud:
    config:
      server:
        git:
          # git 地址
          uri: https://github.com/willingoxjin/springcloud-config-repo.git
          # 是否强制拉取资源文件
          fore-pull: true
          search-paths: '${application}'
        # 属性重载：覆盖配置中心拉取的属性
        overrides:
          test: myTest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

# actuator
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always